# Generated by Django 2.1.10 on 2019-07-22 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_column='YM', max_length=6)),
                ('poi_id', models.CharField(db_column='POI_ID', max_length=18)),
                ('poi', models.CharField(blank=True, db_column='POI', max_length=100, null=True)),
                ('a0', models.CharField(blank=True, max_length=2, null=True)),
                ('a1', models.CharField(blank=True, max_length=3, null=True)),
                ('a2', models.CharField(blank=True, max_length=3, null=True)),
                ('a3', models.CharField(blank=True, max_length=3, null=True)),
                ('arr_an', models.CharField(blank=True, max_length=300, null=True)),
                ('c_rank', models.IntegerField(blank=True, db_column='C_RANK', null=True)),
                ('score_rank', models.FloatField(blank=True, db_column='SCORE_RANK', null=True)),
                ('recommend_id', models.IntegerField(blank=True, db_column='RECOMMEND_ID', null=True)),
                ('recommend_text', models.CharField(blank=True, db_column='RECOMMEND_TEXT', max_length=200, null=True)),
                ('available_flg', models.CharField(blank=True, db_column='AVAILABLE_FLG', max_length=1, null=True)),
                ('available_str_date', models.DateField(blank=True, db_column='AVAILABLE_STR_DATE', null=True)),
                ('available_end_date', models.DateField(blank=True, db_column='AVAILABLE_END_DATE', null=True)),
                ('create_date', models.DateField(db_column='CREATE_DATE')),
            ],
            options={
                'db_table': 'recommend',
            },
        ),
    ]
